### ISSUE TITLE
关于感受野的问题

### ISSUE THREAD

**Issue by Mercuriiio** [liu-vis/DualResidualNetworks#10]
Hi你好，在阅读论文的过程中，我对这句话不是很理解：We also choose the kernel size and dilation rate for each DuRB so that the receptive field of convolution in each DuRB grows its size with L.
我尝试自己计算每一层的感受野，并没有发现有倍数关系。能麻烦您发我一份补充材料吗，下面是我的邮箱：upc_lee@163.com
不胜感激。

**Comment by liu-vis** [comment]
Hello！感谢您阅读我们的文章。
感受野是整体上随着层数加深而扩大，并没有倍数关系。
补充材料贴在arxiv版本下了，请使用下方链接前往：
https://arxiv.org/pdf/1903.08817.pdf

**Comment by Mercuriiio** [comment]
> Hello！感谢您阅读我们的文章。
> 感受野是整体上随着层数加深而扩大，并没有倍数关系。
> 补充材料贴在arxiv版本下了，请使用下方链接前往：
> https://arxiv.org/pdf/1903.08817.pdf

十分感谢！另外还想请问，为何Real-World Noisy Image Dataset+MemNet与DDN Data+RESCAN结果无法测量，是因为实验设置原因还是效果不好？（我跑过RESCAN的实验，好像并没有特殊设置）
期待您的回复。

**Comment by liu-vis** [comment]
这两组实验我都有尝试跑过。
i） MemNet我无法训练出一个可接受的结果。我使用作者给出的caffe代码跑的实验。这也许是因为MemNet对训练参数以及方式有一些要求。
ii）RESCAN是个方便实用的网络，训练确实没有什么特殊设置。可是我记得我在DDN Data上跑出来的数值结果偏低，并不在我个人认为的 合理范围 之内。

我认为 这些网络本身都是 没有问题的。可能它们只是对datasets的bias比较敏感。考虑到对这些网络的公平性，我没有把他们加入到Tables中做比较。

**Comment by Mercuriiio** [comment]
> 这两组实验我都有尝试跑过。
> i） MemNet我无法训练出一个可接受的结果。我使用作者给出的caffe代码跑的实验。这也许是因为MemNet对训练参数以及方式有一些要求。
> ii）RESCAN是个方便实用的网络，训练确实没有什么特殊设置。可是我记得我在DDN Data上跑出来的数值结果偏低，并不在我个人认为的 合理范围 之内。
> 
> 我认为 这些网络本身都是 没有问题的。可能它们只是对datasets的bias比较敏感。考虑到对这些网络的公平性，我没有把他们加入到Tables中做比较。

好的，感谢您的回复，工作真的很amazing，希望工作学习顺利！

**Comment by liu-vis** [comment]
非常感谢！也希望您工作学习都顺利：）
