### ISSUE TITLE
I tried to reproduce DuRN_P results on BSD_gray, but it has a bit gap than yours.

### ISSUE THREAD

**Issue by tiancai-call** [liu-vis/DualResidualNetworks#12]
I used the code (trained/test) and BSD_gray you provided. The results: 28.43 / 0.8130(noise level = 30), 26.29 / 0.7297(noise level = 50), 24.99 / 0.6685(noise level = 70). It has a bit gap than yours. Is there anything special about your training? Or is this result acceptable?

**Comment by liu-vis** [comment]
Hi, thank you for your interest in our work.
I didn't use special tricks in addition to what I uploaded for training.

**Comment by tiancai-call** [comment]
> Hi, thank you for your interest in our work.
> 
> I didn't use special tricks in addition to what I uploaded for training.

Thanks for your response. 
I did not make any changes to the source code in the process of reproducing the results. 
The BSD_gray dataset was downloaded from https://drive.google.com/file/d/1-Q0tCxzisHm7m_qMJfekOy4-oGzfIocj/view?usp=sharing. 
So this result is acceptable?

**Comment by liu-vis** [comment]
uhmm... I am confused. 
By acceptable, do you mean is it okay for me to use your replicated results as a baseline to be compared with? If so, then sure, no problem.

**Comment by tiancai-call** [comment]
> uhmm... I am confused. 
> 
> By acceptable, do you mean is it okay for me to use your replicated results as a baseline to be compared with? If so, then sure, no problem.

I'm sorry for confusing you. 
I mean whether the result of my reproduction is normal, although it is still worse than the one in your paper. 
I understand what you mean.
Thanks for your time.

**Comment by liu-vis** [comment]
No problem and never mind! :)
I see. I think it is acceptable in this sense. 
The difference between two results is within an acceptable error range. This applies to all the three cases (i.e., noise level = 30, 50, 70).
Thank you for trying our network :D
