### ISSUE TITLE
An error when run code

### ISSUE THREAD

**Issue by Jack10001** [liu-vis/DualResidualNetworks#13]
Hello, I try to run your code. But there is an error message. 
![error](https://user-images.githubusercontent.com/34243307/79856856-7e794f80-83ff-11ea-8a0e-cb5a97bf3c2a.PNG)

And I want to know why.

**Comment by liu-vis** [comment]
Hello, thank you for trying our work and sorry for the late reply.
I am sorry I cannot reproduce the error you found.
It seems that you are running the code on Windows. 
 - Please check if Pytorch is correctly installed.
 - Please check if the paths are set correctly. Please first try editing [ line: 39 ] as written below to see if the problem solved.
    [ line: 39 ] Change 「data_root  = '../data/' +data_name+'/train/'」 to  「data_root  = '../data/' +data_name+'/'」
