### ISSUE TITLE
about the additive Gaussian noise removal

### ISSUE THREAD

**Issue by xiaotongtt** [liu-vis/DualResidualNetworks#14]
Thanks for your interesting work! I want to ask about the task of additive Gaussian noise removal. Are the different levels of noise dataset ( i.e., 30, 50, 70) trained in a model together or trained separately for each level?

**Comment by liu-vis** [comment]
Thank you for your interest in our work!
The three levels of noise are used together for training a single model.
A level of noise is randomly chosen to generate noise added to a batch of inputs in each forward.
