### ISSUE TITLE
How to run my own image with motion_blur.py?

### ISSUE THREAD

**Issue by Senwang98** [liu-vis/DualResidualNetworks#15]
Thanks for your amazing work, my current work need to use your motion_blur.py, it can work when i use CarDataset,but how can i run my own image for test?

**Comment by Senwang98** [comment]
Maybe i need to run DeblurGAN to get shape image firstly?

**Comment by liu-vis** [comment]
Thank you for your interest in our work!
Just load the image, convert it to Tensor, and put it into the network. Specifically, 
   - 1) Make a copy of motion_blur.py
   - 2) Remove / Ignore the code related to using the dataloader.
   - 3) Load your image by i) or ii) written below:
        - i)  blur = cv2.imread( pth_to_image ) , then , blur = cv2.cvtColor(blur, cv2.COLOR_BGR2RGB)
        - ii) blur = Image.open( pth_to_image )
   - 4) Convert the image into Tensor using transforms.ToTensor()
   - 5) Put that into the network and get the result. Please see [ line: 74 - 80 ] in motion_blur.py for reference.

**Comment by Senwang98** [comment]
Ok, thank you!
