### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by raysun0501** [liu-vis/DualResidualNetworks#8]
Dear authors, hi.
    There are some questions I want to ask you:
         Your readme writes the environment is python3.7 + PyTorch 1.2, but when I clone your code, I find it has no different with the preceding version of code, which is python2.7 + PyTorch0.31;
         Can you update your code version as you say?

**Comment by liu-vis** [comment]
Hello RaySun,

There should be no problem with running the code on both versions of environment.
Please let me know if you find a bug.
