### ISSUE TITLE
Experimental environments

### ISSUE THREAD

**Issue by dongheehand** [liu-vis/DualResidualNetworks#9]
I am wondering about the experimental environments

1. The number of gpus for training
2. The gpu you used for training

Thank you!

**Comment by liu-vis** [comment]
Hi, thank you for your interest in our work. 
I used "GTX 1080 ti" for this work.

Sorry I don't exactly remember the number of GPU used for each training. Those written below are the probable setting.
i)  1 GPU for noise removal, rain-streak removal.
ii) 2 GPUs for raindrop removal, motion blur removal.
iii) 4 GPUs for haze removal.
